name: Aplicar sugerencias de IA

on:
  workflow_dispatch:

jobs:
  aplicar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Ejecutar script aplicar_sugerencias.py
        run: python aplicar_sugerencias.py

      - name: Hacer commit y push de los cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Aplicar sugerencias automáticas de IA"
          git push
