name: Enviar a IA

on:
  workflow_dispatch:

jobs:
  enviar_a_ia:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Ejecutar script enviar_a_ia.py
        run: python enviar_a_ia.py

      - name: Guardar archivo de sugerencias
        uses: actions/upload-artifact@v4
        with:
          name: sugerencias
          path: sugerencias.md
